### PR TITLE
#4 Fix authentication for API calls

### LINKED ISSUE #4: Addition of a to-do item doesn't work

### PR DESCRIPTION
**Pull request by alexeykuptsov**

### CODE REVIEW

File: App/wwwroot/js/site.js [hunk 1]
```diff
@@ -28,25 +28,36 @@ function addItem() {
         name: addNameTextbox.value.trim()
     };
 
+    let authToken = localStorage.getItem('authToken');
```
Comment (Olsattt) [inline App/wwwroot/js/site.js:61]: What is it?

Comment (alexeykuptsov) [reply App/wwwroot/js/site.js:61]: This is a JWT token that is implemented by following this video https://youtu.be/v7q3pEK1EA0 . The token is saved on successful login and is used to provide access to Web API actions.

**Review by Olsattt — APPROVED** [review]
